name: user_role_management
description: "Takım Yönetim Sistemi - Firebase entegrasyonlu kullanıcı rol yönetimi uygulaması"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  curved_navigation_bar: ^1.0.6
  rxdart: ^0.28.0

  # State Management
  provider: ^6.1.2

  # UI Components
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

  # Utilities
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:


    - assets/yasunapp_logo.png
